#!/bin/bash
echo ""
source secret
echo "### Deploying website"
cd ..
git add .
git reset -- jekyll-code/*
git commit * -m "new website release"
git push
cd -
echo ""
echo "### Purging cloudfare cache"
curl -X DELETE "https://api.cloudflare.com/client/v4/zones/27afa631b80b5c1ebc07c87e5e6b708f/purge_cache" \
     -H "X-Auth-Email: jeroen.mols.be@gmail.com" \
     -H "X-Auth-Key: $CLOUDFAREAPIKEY" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}' | grep "success\":true" &> /dev/null
echo ""
if [ $? == 0 ]; then
   echo "Cache cleared success"
else
   echo "FAILED to clear cache"
fi
echo ""
echo "### Done"
